//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2084_assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        public Authors()
        {
            this.Comics = new HashSet<Comics>();
        }
    
        public int AuthorID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Comics> Comics { get; set; }
    }
}
