//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2084_assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comics
    {
        public int ComicID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public int Issue { get; set; }
        public int AuthorID { get; set; }
        public int PublisherID { get; set; }
        public int UserID { get; set; }
    
        public virtual Authors Author1 { get; set; }
        public virtual Publishers Publisher1 { get; set; }
        public virtual Users User { get; set; }
    }
}
